FROM fj0rd/test

RUN set -eux \
  ; export https_proxy=http://192.168.31.111:1081 \
  ; ln -sf /etc/skel/.config /root \
  ; NVIM_BOOTSTRAP=1 \
    nvim -u /root/.config/nvim/init.lua --headless \
    +'autocmd User PackerComplete quitall' \
    +'lua require("packer").sync()'
